export const GET_MOVIES = 'GET_MOVIES';
export const GET_GENRES = 'GET_GENRES';
export const GET_GENRE = 'GET_GENRE';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';
export const SWITCH_THEME_TRUE = 'SWITCH_THEME_TRUE';
export const SWITCH_THEME_FALSE = 'SWITCH_THEME_FALSE';
